version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sohopathi
      - JWT_SECRET=superlongsecret
      - SMYTHOS_URL=https://api.smythos.example
      - SMYTHOS_API_KEY=change_for_prod
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
